name: pr20221029
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1 # 1.0.1@教學
  cloud_firestore: ^4.0.3  #firebase
  firebase_storage: ^11.0.3 #最新版才能跑
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  firebase_auth: ^4.1.0 # 1.0.1@教學
  google_sign_in: ^5.4.2 # 5.0.0@教學
  footer: ^0.0.4 #版權底部
  http: ^0.13.3 # 抓取GoogleSheets資料 https://www.syncfusion.com/kb/12826/how-to-get-the-data-from-google-sheet-and-load-it-to-the-flutter-calendar-sfcalendar
  fluttertoast: ^8.1.1 #彈出訊息
  csv: ^5.0.1 #讀取csv檔案

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^4.6.5

flutter:
  uses-material-design: true
  #這邊縮排必須對齊.............
  assets:
    - assets/images/
