// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKAkiww1pOYf3yxH-_A7iLHYnR1HOdyG8',
    appId: '1:858270503530:web:2f15ff847ecc80f345f013',
    messagingSenderId: '858270503530',
    projectId: 'fir-20221026',
    authDomain: 'fir-20221026.firebaseapp.com',
    storageBucket: 'fir-20221026.appspot.com',
    measurementId: 'G-8SLQYV7302',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQytLcUF417aSObTYIz9_kPNh7G31QMg',
    appId: '1:858270503530:android:1edcc81139fada2945f013',
    messagingSenderId: '858270503530',
    projectId: 'fir-20221026',
    storageBucket: 'fir-20221026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqOQ2rSEhU0HrtQr-21BQf956nxa-qcS0',
    appId: '1:858270503530:ios:4d70ecde827e59cc45f013',
    messagingSenderId: '858270503530',
    projectId: 'fir-20221026',
    storageBucket: 'fir-20221026.appspot.com',
    iosClientId: '858270503530-c4i1gu1a2bu311pfnu809ao839p5nid0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pr20221029',
  );
}
